image:
  repository: /products-app-devops-frontend
  tag: "78fb94ac509e12e4566a20ee5ec33360ebff1e0c"
replicaCount: 1
ingress:
  enabled: true
  host: pern-app.local
  annotations: {}
env:
  VITE_API_URL: "/api"
  CONFIG_VAR: "CONFIG VAR from configmap"
  CONFIG_VAR1: "CONFIG VAR 1"
  CONFIG_VAR2: "CONFIG VAR 2"
configs:
  name: frontend-configs
