apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  VITE_API_URL: "{{ .Values.env.VITE_API_URL }}"
  CONFIG_VAR: "{{ .Values.env.CONFIG_VAR }}"
  CONFIG_VAR1: "{{ .Values.env.CONFIG_VAR1 }}"
  CONFIG_VAR2: "{{ .Values.env.CONFIG_VAR2 }}"
  
