apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-external-secret
  namespace: pern-dev   # The namespace where the Kubernetes Secret will be created
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: backend-secret
  data:
  - secretKey: DATABASE_URL   #as defined in backend deployment
    remoteRef:
      key: dbconn
      property: dburl

