apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: pern-dev
spec:
  provider:
    vault:
      server: "http://host.minikube.internal:8200"
      path: "app"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token-secret"      # manually created secret
          key: "token"
